### ISSUE TITLE
GCP accuracies

### ISSUE THREAD

**Issue by geomohre** [OpenDroneMap/odm_data_helenenschacht#1]
Hi there, thanks for sharing the data! The GCPs look like they were measured using DGPS, is that correct? Just asking to approximate the accuracies. 
Cheers

**Comment by Saijin-Naib** [comment]
I've asked the original contributor of the data, so hopefully I can update you soon.

**Comment by Saijin-Naib** [comment]
GCPs were taken via Emlid Reach RS2 with NTRIP connection, the data provider is estimating 1-2cm accuracy.
